plugins:
  qa_tags:
    client: true
    type: list
    default: 'question'
  qa_show_topic_tip:
    client: true
    default: true
  qa_enabled:
    client: true
    default: true
  qa_disable_like_on_answers:
    client: true
    default: false
