plugins:
  qa_tags:
    client: true
    type: list
    default: 'question'
  qa_show_topic_tip:
    client: true
    default: true
  qa_enabled:
    client: true
    default: true
  qa_disable_like_on_answers:
    client: true
    default: false
  qa_undo_vote_action_window:
    default: 10
  qa_comments_default:
    default: 3
    client: true
  qa_tl1_vote_limit: 1
  qa_tl2_vote_limit: 3
  qa_tl3_vote_limit: 10
  qa_tl4_vote_limit: 100
  qa_allow_multiple_votes_per_post:
    default: false
    client: true
